### ISSUE TITLE
Aragon.Desktop.AppImage - A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by tosho** [aragon/aragon-desktop#59]
I tried to run Aragon.Desktop.AppImage from terminal this is what I get:
```
$ ./Aragon.Desktop.AppImage       

A JavaScript error occurred in the main process
Uncaught Exception:
Error: /tmp/.mount_Aragonc4hyFG/resources/app/node_modules/scrypt/build/Release/scrypt.node: invalid ELF header
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:160:31)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/tmp/.mount_Aragonc4hyFG/resources/app/node_modules/scrypt/index.js:3:20)
    at Object.<anonymous> (/tmp/.mount_Aragonc4hyFG/resources/app/node_modules/scrypt/index.js:388:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
```
running Ubuntu 18.04, node 11.6.0, npm 6.7.0

**Comment by maurelian** [comment]
I have the exact same issue and error message, but installed with `snap install --dangerous Aragon.Desktop.snap`

running Ubuntu 18.04, node 10.13.0, npm 6.4.1

**Comment by tosho** [comment]
> I have the exact same issue and error message, but installed with `snap install --dangerous Aragon.Desktop.snap`
> 
> running Ubuntu 18.04, node 10.13.0, npm 6.4.1

$ aragon-desktop 

` rm: cannot remove '/home/tosho/.config/ibus/bus/112edb11675b41d3a9c682669926b1e6-unix-0': Permission denied
ln: '/home/tosho/.config/ibus/bus' and '/home/tosho/.config/ibus/bus' are the same file
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /snap/aragon-desktop/x1/resources/app/node_modules/scrypt/build/Release/scrypt.node: invalid ELF header
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:160:31)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/snap/aragon-desktop/x1/resources/app/node_modules/scrypt/index.js:3:20)
    at Object.<anonymous> (/snap/aragon-desktop/x1/resources/app/node_modules/scrypt/index.js:388:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
`
 
 I did: `sudo apt install libcanberra-gtk-module libcanberra-gtk3-module` but it's already installed

` 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libcanberra-gtk3-module is already the newest version (0.30-5ubuntu1).
libcanberra-gtk-module is already the newest version (0.30-5ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
`
also  `sudo apt-get install libcanberra-gtk-module:i386` didn't do anything. I got the same error

**Comment by sohkai** [comment]
Looks like this was because I built the linux distributions on macOS instead of on linux. I'll remove the other images from the releases.

We should set up distributions on Travis instead: https://www.electron.build/multi-platform-build.

**Comment by sohkai** [comment]
@tosho @maurelian This should be fixed now, we've regened the linux builds on an actual linux machine 😄.

**Comment by maurelian** [comment]
the snap package is working now, thanks!
