### ISSUE TITLE
Couldn't start client

### ISSUE THREAD

**Issue by AthrunArthur** [aragon/aragon-desktop#80]
Got error like this after 'npm start',

App threw an error during load
TypeError: Cannot read property 'pin' of undefined
    at Object.<anonymous> (/Users/me/git/aragon-desktop/src/lib/ipfs-caching.js:12:57)
    at Object.<anonymous> (/Users/me/git/aragon-desktop/src/lib/ipfs-caching.js:99:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/me/git/aragon-desktop/src/main.js:15:5)
    at Object.<anonymous> (/Users/me/git/aragon-desktop/src/main.js:183:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at loadApplicationPackage (/Users/me/git/aragon-desktop/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js:119:12)
    at Object.<anonymous> (/Users/me/git/aragon-desktop/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js:164:5)
    at Object.<anonymous> (/Users/me/git/aragon-desktop/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js:204:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Object.<anonymous> (/Users/me/git/aragon-desktop/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/init.js:188:8)
    at Object.<anonymous> (/Users/me/git/aragon-desktop/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/init.js:190:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)

**Comment by 0xGabi** [comment]
@AthrunArthur Hi and thanks for reporting this issue, I'll take a look and let you know

**Comment by 0xGabi** [comment]
@AthrunArthur would you mind give me a bit of context of you current OS to try reproduce on a VM. Thanks
